services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $bundle: '@Zikula\ContentModule\ZikulaContentModule'
            $twigLoader: '@twig.loader'

    Zikula\ContentModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Base/bootstrap.php,Tests,vendor}'

    Zikula\ContentModule\Helper\:
        resource: '../../Helper/*'
        lazy: true

    # public because EntityLifecycleListener accesses this using container
    Zikula\ContentModule\Entity\Factory\EntityFactory:
        public: true
    
    Zikula\ContentModule\Form\Handler\:
        resource: '../../Form/Handler'
        calls:
            - setLockingApi: ['@?Zikula\PageLockModule\Api\LockingApi']
    
    Zikula\ContentModule\Helper\ViewHelper:
        arguments:
            $pageVars: '@zikula_core.common.theme.pagevars'
    
    Zikula\ContentModule\Listener\EntityLifecycleListener:
        tags: ['doctrine.event_subscriber']
    
    # public because EntityLifecycleListener accesses this using container
    Zikula\ContentModule\Listener\LoggableListener:
        public: true
    
    Zikula\ContentModule\Menu\MenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: createItemActionsMenu, alias: zikulaContentMenuItemActions }
            - { name: knp_menu.menu_builder, method: createViewActionsMenu, alias: zikulaContentMenuViewActions }
    
    stof_doctrine_extensions.listener.sluggable:
        class: '%stof_doctrine_extensions.listener.sluggable.class%'
        calls:
            - setAnnotationReader: ['@annotation_reader']
            - setTransliterator: [[Zikula\ContentModule\Helper\SlugTransliterator, 'transliterate']]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
